/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubesphere.io/api/virtualization/v1alpha1"
	scheme "kubesphere.io/kubesphere/pkg/client/clientset/versioned/scheme"
)

// VirtualMachineSpecsGetter has a method to return a VirtualMachineSpecInterface.
// A group's client should implement this interface.
type VirtualMachineSpecsGetter interface {
	VirtualMachineSpecs() VirtualMachineSpecInterface
}

// VirtualMachineSpecInterface has methods to work with VirtualMachineSpec resources.
type VirtualMachineSpecInterface interface {
	Create(ctx context.Context, virtualMachineSpec *v1alpha1.VirtualMachineSpec, opts v1.CreateOptions) (*v1alpha1.VirtualMachineSpec, error)
	Update(ctx context.Context, virtualMachineSpec *v1alpha1.VirtualMachineSpec, opts v1.UpdateOptions) (*v1alpha1.VirtualMachineSpec, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VirtualMachineSpec, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VirtualMachineSpecList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineSpec, err error)
	VirtualMachineSpecExpansion
}

// virtualMachineSpecs implements VirtualMachineSpecInterface
type virtualMachineSpecs struct {
	client rest.Interface
}

// newVirtualMachineSpecs returns a VirtualMachineSpecs
func newVirtualMachineSpecs(c *VirtualizationV1alpha1Client) *virtualMachineSpecs {
	return &virtualMachineSpecs{
		client: c.RESTClient(),
	}
}

// Get takes name of the virtualMachineSpec, and returns the corresponding virtualMachineSpec object, and an error if there is any.
func (c *virtualMachineSpecs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualMachineSpec, err error) {
	result = &v1alpha1.VirtualMachineSpec{}
	err = c.client.Get().
		Resource("virtualmachinespecs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VirtualMachineSpecs that match those selectors.
func (c *virtualMachineSpecs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualMachineSpecList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VirtualMachineSpecList{}
	err = c.client.Get().
		Resource("virtualmachinespecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested virtualMachineSpecs.
func (c *virtualMachineSpecs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("virtualmachinespecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a virtualMachineSpec and creates it.  Returns the server's representation of the virtualMachineSpec, and an error, if there is any.
func (c *virtualMachineSpecs) Create(ctx context.Context, virtualMachineSpec *v1alpha1.VirtualMachineSpec, opts v1.CreateOptions) (result *v1alpha1.VirtualMachineSpec, err error) {
	result = &v1alpha1.VirtualMachineSpec{}
	err = c.client.Post().
		Resource("virtualmachinespecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualMachineSpec).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a virtualMachineSpec and updates it. Returns the server's representation of the virtualMachineSpec, and an error, if there is any.
func (c *virtualMachineSpecs) Update(ctx context.Context, virtualMachineSpec *v1alpha1.VirtualMachineSpec, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineSpec, err error) {
	result = &v1alpha1.VirtualMachineSpec{}
	err = c.client.Put().
		Resource("virtualmachinespecs").
		Name(virtualMachineSpec.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualMachineSpec).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the virtualMachineSpec and deletes it. Returns an error if one occurs.
func (c *virtualMachineSpecs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("virtualmachinespecs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *virtualMachineSpecs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("virtualmachinespecs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched virtualMachineSpec.
func (c *virtualMachineSpecs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineSpec, err error) {
	result = &v1alpha1.VirtualMachineSpec{}
	err = c.client.Patch(pt).
		Resource("virtualmachinespecs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
