/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubesphere.io/api/virtualization/v1alpha1"
)

// VirtualMachineSpecLister helps list VirtualMachineSpecs.
// All objects returned here must be treated as read-only.
type VirtualMachineSpecLister interface {
	// List lists all VirtualMachineSpecs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.VirtualMachineSpec, err error)
	// Get retrieves the VirtualMachineSpec from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.VirtualMachineSpec, error)
	VirtualMachineSpecListerExpansion
}

// virtualMachineSpecLister implements the VirtualMachineSpecLister interface.
type virtualMachineSpecLister struct {
	indexer cache.Indexer
}

// NewVirtualMachineSpecLister returns a new VirtualMachineSpecLister.
func NewVirtualMachineSpecLister(indexer cache.Indexer) VirtualMachineSpecLister {
	return &virtualMachineSpecLister{indexer: indexer}
}

// List lists all VirtualMachineSpecs in the indexer.
func (s *virtualMachineSpecLister) List(selector labels.Selector) (ret []*v1alpha1.VirtualMachineSpec, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.VirtualMachineSpec))
	})
	return ret, err
}

// Get retrieves the VirtualMachineSpec from the index for a given name.
func (s *virtualMachineSpecLister) Get(name string) (*v1alpha1.VirtualMachineSpec, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("virtualmachinespec"), name)
	}
	return obj.(*v1alpha1.VirtualMachineSpec), nil
}
