/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubesphere.io/api/virtualization/v1alpha1"
)

// FakeVirtualMachineSpecs implements VirtualMachineSpecInterface
type FakeVirtualMachineSpecs struct {
	Fake *FakeVirtualizationV1alpha1
}

var virtualmachinespecsResource = schema.GroupVersionResource{Group: "virtualization.kubesphere.io", Version: "v1alpha1", Resource: "virtualmachinespecs"}

var virtualmachinespecsKind = schema.GroupVersionKind{Group: "virtualization.kubesphere.io", Version: "v1alpha1", Kind: "VirtualMachineSpec"}

// Get takes name of the virtualMachineSpec, and returns the corresponding virtualMachineSpec object, and an error if there is any.
func (c *FakeVirtualMachineSpecs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualMachineSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(virtualmachinespecsResource, name), &v1alpha1.VirtualMachineSpec{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSpec), err
}

// List takes label and field selectors, and returns the list of VirtualMachineSpecs that match those selectors.
func (c *FakeVirtualMachineSpecs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualMachineSpecList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(virtualmachinespecsResource, virtualmachinespecsKind, opts), &v1alpha1.VirtualMachineSpecList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSpecList), err
}

// Watch returns a watch.Interface that watches the requested virtualMachineSpecs.
func (c *FakeVirtualMachineSpecs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(virtualmachinespecsResource, opts))
}

// Create takes the representation of a virtualMachineSpec and creates it.  Returns the server's representation of the virtualMachineSpec, and an error, if there is any.
func (c *FakeVirtualMachineSpecs) Create(ctx context.Context, virtualMachineSpec *v1alpha1.VirtualMachineSpec, opts v1.CreateOptions) (result *v1alpha1.VirtualMachineSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(virtualmachinespecsResource, virtualMachineSpec), &v1alpha1.VirtualMachineSpec{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSpec), err
}

// Update takes the representation of a virtualMachineSpec and updates it. Returns the server's representation of the virtualMachineSpec, and an error, if there is any.
func (c *FakeVirtualMachineSpecs) Update(ctx context.Context, virtualMachineSpec *v1alpha1.VirtualMachineSpec, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(virtualmachinespecsResource, virtualMachineSpec), &v1alpha1.VirtualMachineSpec{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSpec), err
}

// Delete takes name of the virtualMachineSpec and deletes it. Returns an error if one occurs.
func (c *FakeVirtualMachineSpecs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(virtualmachinespecsResource, name), &v1alpha1.VirtualMachineSpec{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualMachineSpecs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(virtualmachinespecsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VirtualMachineSpecList{})
	return err
}

// Patch applies the patch and returns the patched virtualMachineSpec.
func (c *FakeVirtualMachineSpecs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(virtualmachinespecsResource, name, pt, data, subresources...), &v1alpha1.VirtualMachineSpec{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSpec), err
}
